---
# handlers file for base_config
- name: Generate locales
  ansible.builtin.command: locale-gen
  listen: "Generate locales" # Explicitly listen for clarity

- name: Update hwclock
  ansible.builtin.command: hwclock --systohc
  listen: "Update hwclock"